# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVdVQF6bNnqFrw6V7fTKgtM1zXPd_P2T
"""

!pip install pandas

"""to install library 'pandas'"""

import pandas as pd

"""to import 'pandas' as pd"""

from google.colab import drive

"""to import data from drive"""

drive.mount('/content/drive')

"""to connect google drive to colab"""

path = '/content/drive/MyDrive/data.csv'

"""to save csv file in var 'path'"""

df = pd.read_csv(path)

df.head(10)

"""10 data awal"""

df.tail()

"""5 data terakhir"""

df.loc[2]

"""untuk mengakses kolom berdasarkan yang kalian inginkan"""

df.iloc[1:100]

"""memilih baris dari indeks tertentu sampai tertentu"""

df['Context'] [1:10]

"""menampilkan nilai dari kolom yang kalian inginkan beserta mau berapa"""